name: flutter_gallery_app
description: "Flutter Image Gallery project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  equatable: ^2.0.5
  fpdart: ^1.1.0
  logger: ^2.3.0
  flutter_bloc: ^8.1.5
  infinite_scroll_pagination: ^4.0.0
  pretty_dio_logger: ^1.3.1
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0


flutter:

  uses-material-design: true
